filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
    fields:
      logtype: syslog

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  protocol: "https"
  ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/ca/ca.crt"]

