metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - memory
      - network
      - diskio
    enabled: true

  - module: docker
    metricsets:
      - container
      - cpu
      - memory
    hosts: ["unix:///var/run/docker.sock"]
    enabled: true

output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  protocol: "https"
  ssl.certificate_authorities: ["/usr/share/metricbeat/config/certs/ca/ca.crt"]

